version: '2'
services:
    truckwash-app:
        image: truckwash
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://truckwash-mysql:3306/truckwash?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    truckwash-mysql:
        extends:
            file: mysql.yml
            service: truckwash-mysql
